version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-inventory
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: inventory
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
