// Dummy data for inventory management system
export const categories = [
  {
    id: 1,
    name: "Fresh Produce",
    description: "Fruits, vegetables, and fresh herbs",
    itemCount: 145,
    lowStockItems: 12,
    totalValue: 15420.5,
    color: "bg-green-50 border-green-200",
  },
  {
    id: 2,
    name: "Dairy & Eggs",
    description: "Milk, cheese, yogurt, and fresh eggs",
    itemCount: 89,
    lowStockItems: 5,
    totalValue: 8750.25,
    color: "bg-blue-50 border-blue-200",
  },
  {
    id: 3,
    name: "Meat & Seafood",
    description: "Fresh and frozen meat, poultry, and seafood",
    itemCount: 67,
    lowStockItems: 8,
    totalValue: 12340.75,
    color: "bg-red-50 border-red-200",
  },
  {
    id: 4,
    name: "Bakery",
    description: "Fresh bread, pastries, and baked goods",
    itemCount: 45,
    lowStockItems: 3,
    totalValue: 3250.0,
    color: "bg-yellow-50 border-yellow-200",
  },
  {
    id: 5,
    name: "Frozen Foods",
    description: "Frozen meals, ice cream, and frozen vegetables",
    itemCount: 123,
    lowStockItems: 15,
    totalValue: 9875.3,
    color: "bg-cyan-50 border-cyan-200",
  },
  {
    id: 6,
    name: "Beverages",
    description: "Soft drinks, juices, water, and alcoholic beverages",
    itemCount: 156,
    lowStockItems: 7,
    totalValue: 11200.45,
    color: "bg-purple-50 border-purple-200",
  },
  {
    id: 7,
    name: "Snacks & Candy",
    description: "Chips, cookies, candy, and confectionery",
    itemCount: 98,
    lowStockItems: 4,
    totalValue: 4560.8,
    color: "bg-orange-50 border-orange-200",
  },
  {
    id: 8,
    name: "Health & Beauty",
    description: "Personal care, cosmetics, and health products",
    itemCount: 134,
    lowStockItems: 9,
    totalValue: 7890.6,
    color: "bg-pink-50 border-pink-200",
  },
  {
    id: 9,
    name: "Household Items",
    description: "Cleaning supplies, paper products, and home essentials",
    itemCount: 87,
    lowStockItems: 6,
    totalValue: 5670.25,
    color: "bg-gray-50 border-gray-200",
  },
]

// Customer orders data
export const customerOrders = [
  {
    id: "ORD-2024-001",
    date: "2024-01-15",
    customerName: "John Smith",
    customerEmail: "john.smith@email.com",
    items: [
      { name: "Organic Bananas", quantity: 3, price: 4.99 },
      { name: "Whole Milk", quantity: 1, price: 3.49 },
      { name: "Bread Loaf", quantity: 2, price: 2.99 },
    ],
    totalAmount: 14.46,
    status: "completed",
    paymentMethod: "credit-card",
    orderType: "pickup",
  },
  {
    id: "ORD-2024-002",
    date: "2024-01-15",
    customerName: "Sarah Johnson",
    customerEmail: "sarah.j@email.com",
    items: [
      { name: "Chicken Breast", quantity: 2, price: 12.99 },
      { name: "Mixed Vegetables", quantity: 1, price: 5.49 },
    ],
    totalAmount: 18.48,
    status: "preparing",
    paymentMethod: "debit-card",
    orderType: "delivery",
  },
  {
    id: "ORD-2024-003",
    date: "2024-01-14",
    customerName: "Mike Davis",
    customerEmail: "mike.davis@email.com",
    items: [
      { name: "Ice Cream", quantity: 1, price: 6.99 },
      { name: "Frozen Pizza", quantity: 2, price: 8.99 },
      { name: "Orange Juice", quantity: 1, price: 4.49 },
    ],
    totalAmount: 20.47,
    status: "ready",
    paymentMethod: "cash",
    orderType: "pickup",
  },
  {
    id: "ORD-2024-004",
    date: "2024-01-14",
    customerName: "Emily Wilson",
    customerEmail: "emily.w@email.com",
    items: [
      { name: "Shampoo", quantity: 1, price: 8.99 },
      { name: "Toothpaste", quantity: 2, price: 4.99 },
    ],
    totalAmount: 13.98,
    status: "cancelled",
    paymentMethod: "credit-card",
    orderType: "delivery",
  },
  {
    id: "ORD-2024-005",
    date: "2024-01-13",
    customerName: "Robert Brown",
    customerEmail: "rob.brown@email.com",
    items: [
      { name: "Cleaning Spray", quantity: 3, price: 3.99 },
      { name: "Paper Towels", quantity: 2, price: 5.99 },
    ],
    totalAmount: 15.97,
    status: "completed",
    paymentMethod: "debit-card",
    orderType: "pickup",
  },
]

export const purchaseOrders = [
  {
    id: "PO-2024-001",
    date: "2024-01-15",
    supplier: "Fresh Farm Suppliers",
    items: 25,
    totalCost: 2450.75,
    status: "in-stock",
    expectedDate: "2024-01-15",
    category: "Fresh Produce",
  },
  {
    id: "PO-2024-002",
    date: "2024-01-14",
    supplier: "Dairy Direct Co.",
    items: 15,
    totalCost: 1890.5,
    status: "low-stock",
    expectedDate: "2024-01-18",
    category: "Dairy & Eggs",
  },
  {
    id: "PO-2024-003",
    date: "2024-01-13",
    supplier: "Premium Meats Ltd",
    items: 12,
    totalCost: 3250.0,
    status: "out-of-stock",
    expectedDate: "2024-01-16",
    category: "Meat & Seafood",
  },
  {
    id: "PO-2024-004",
    date: "2024-01-12",
    supplier: "Beverage Distributors",
    items: 45,
    totalCost: 1750.25,
    status: "in-stock",
    expectedDate: "2024-01-12",
    category: "Beverages",
  },
  {
    id: "PO-2024-005",
    date: "2024-01-11",
    supplier: "Frozen Foods Express",
    items: 30,
    totalCost: 2100.8,
    status: "reorder-needed",
    expectedDate: "2024-01-19",
    category: "Frozen Foods",
  },
  {
    id: "PO-2024-006",
    date: "2024-01-10",
    supplier: "Bakery Fresh Supply",
    items: 8,
    totalCost: 450.0,
    status: "overstocked",
    expectedDate: "2024-01-13",
    category: "Bakery",
  },
]

// Update the inventoryItems array to match the mongoose schema
export const inventoryItems = [
  {
    id: 1,
    name: "Organic Bananas",
    sku: "BAN-ORG-001",
    barcode: "1234567890123",
    categoryId: 1,
    supplierId: 1,
    brand: "Fresh Farms",
    description: "Fresh organic bananas from local farms",
    unit: "kg",
    costPrice: 2.5,
    sellingPrice: 4.99,
    discountPrice: 4.49,
    initialStock: 45,
    lowStockThreshold: 10,
    weight: 0.15,
    dimensions: "15cm x 3cm",
    isPerishable: true,
    isActive: true,
    trackInventory: true,
    requiresRefrigeration: false,
    isOrganic: true,
  },
  {
    id: 2,
    name: "Red Apples",
    sku: "APP-RED-001",
    barcode: "1234567890124",
    categoryId: 1,
    supplierId: 1,
    brand: "Orchard Fresh",
    description: "Crisp red apples",
    unit: "kg",
    costPrice: 1.8,
    sellingPrice: 3.49,
    discountPrice: 0,
    initialStock: 8,
    lowStockThreshold: 15,
    weight: 0.18,
    dimensions: "8cm diameter",
    isPerishable: true,
    isActive: true,
    trackInventory: true,
    requiresRefrigeration: false,
    isOrganic: false,
  },
  {
    id: 3,
    name: "Organic Carrots",
    sku: "CAR-ORG-001",
    barcode: "1234567890125",
    categoryId: 1,
    supplierId: 2,
    brand: "Green Valley",
    description: "Fresh organic carrots",
    unit: "kg",
    costPrice: 1.2,
    sellingPrice: 2.99,
    discountPrice: 2.49,
    initialStock: 0,
    lowStockThreshold: 20,
    weight: 0.12,
    dimensions: "20cm x 2cm",
    isPerishable: true,
    isActive: true,
    trackInventory: true,
    requiresRefrigeration: false,
    isOrganic: true,
  },
  {
    id: 4,
    name: "Whole Milk",
    sku: "MLK-WHO-001",
    barcode: "1234567890126",
    categoryId: 2,
    supplierId: 3,
    brand: "Dairy Fresh",
    description: "Fresh whole milk",
    unit: "liter",
    costPrice: 1.8,
    sellingPrice: 3.49,
    discountPrice: 0,
    initialStock: 25,
    lowStockThreshold: 12,
    weight: 1.03,
    dimensions: "25cm x 6cm x 6cm",
    isPerishable: true,
    isActive: true,
    trackInventory: true,
    requiresRefrigeration: true,
    isOrganic: false,
  },
  {
    id: 5,
    name: "Cheddar Cheese",
    sku: "CHE-CHE-001",
    barcode: "1234567890127",
    categoryId: 2,
    supplierId: 3,
    brand: "Artisan Dairy",
    description: "Sharp cheddar cheese",
    unit: "piece",
    costPrice: 3.5,
    sellingPrice: 5.99,
    discountPrice: 5.49,
    initialStock: 5,
    lowStockThreshold: 8,
    weight: 0.25,
    dimensions: "10cm x 8cm x 3cm",
    isPerishable: true,
    isActive: true,
    trackInventory: true,
    requiresRefrigeration: true,
    isOrganic: false,
  },
]

// Add suppliers data to match the schema
export const suppliers = [
  {
    id: 1,
    name: "Fresh Farm Suppliers",
    contactPerson: "John Smith",
    email: "john@freshfarm.com",
    phone: "+1-555-0101",
  },
  {
    id: 2,
    name: "Organic Growers Co.",
    contactPerson: "Sarah Johnson",
    email: "sarah@organicgrowers.com",
    phone: "+1-555-0102",
  },
  {
    id: 3,
    name: "Dairy Direct Co.",
    contactPerson: "Mike Wilson",
    email: "mike@dairydirect.com",
    phone: "+1-555-0103",
  },
]

export const inventoryStats = {
  totalCategories: categories.length,
  totalItems: categories.reduce((sum, cat) => sum + cat.itemCount, 0),
  lowStockItems: categories.reduce((sum, cat) => sum + cat.lowStockItems, 0),
  totalValue: categories.reduce((sum, cat) => sum + cat.totalValue, 0),
}

export const orderStats = {
  totalOrders: purchaseOrders.length,
  inStock: purchaseOrders.filter((o) => o.status === "in-stock").length,
  lowStock: purchaseOrders.filter((o) => o.status === "low-stock").length,
  outOfStock: purchaseOrders.filter((o) => o.status === "out-of-stock").length,
  reorderNeeded: purchaseOrders.filter((o) => o.status === "reorder-needed").length,
  overstocked: purchaseOrders.filter((o) => o.status === "overstocked").length,
}

export const customerOrderStats = {
  totalOrders: customerOrders.length,
  completed: customerOrders.filter((o) => o.status === "completed").length,
  preparing: customerOrders.filter((o) => o.status === "preparing").length,
  ready: customerOrders.filter((o) => o.status === "ready").length,
  cancelled: customerOrders.filter((o) => o.status === "cancelled").length,
  totalRevenue: customerOrders
    .filter((o) => o.status === "completed")
    .reduce((sum, order) => sum + order.totalAmount, 0),
}

// Add reorder-specific data and functions
export const reorderStats = {
  totalProductsNeedingReorder: 15,
  outOfStockItems: 3,
  lowStockItems: 8,
  estimatedReorderValue: 4250.75,
  pendingOrders: 4,
  suppliersInvolved: 5,
}

export const productsNeedingReorder = [
  {
    id: 3,
    name: "Organic Carrots",
    sku: "CAR-ORG-001",
    categoryId: 1,
    categoryName: "Fresh Produce",
    supplierId: 2,
    supplierName: "Organic Growers Co.",
    supplierContact: "sarah@organicgrowers.com",
    currentStock: 0,
    lowStockThreshold: 20,
    unit: "kg",
    costPrice: 1.2,
    sellingPrice: 2.99,
    status: "out-of-stock" as const,
    lastRestocked: "2024-01-10",
    suggestedReorderQuantity: 50,
  },
  {
    id: 2,
    name: "Red Apples",
    sku: "APP-RED-001",
    categoryId: 1,
    categoryName: "Fresh Produce",
    supplierId: 1,
    supplierName: "Fresh Farm Suppliers",
    supplierContact: "john@freshfarm.com",
    currentStock: 8,
    lowStockThreshold: 15,
    unit: "kg",
    costPrice: 1.8,
    sellingPrice: 3.49,
    status: "low-stock" as const,
    lastRestocked: "2024-01-14",
    suggestedReorderQuantity: 30,
  },
  {
    id: 5,
    name: "Cheddar Cheese",
    sku: "CHE-CHE-001",
    categoryId: 2,
    categoryName: "Dairy & Eggs",
    supplierId: 3,
    supplierName: "Dairy Direct Co.",
    supplierContact: "mike@dairydirect.com",
    currentStock: 5,
    lowStockThreshold: 8,
    unit: "piece",
    costPrice: 3.5,
    sellingPrice: 5.99,
    status: "low-stock" as const,
    lastRestocked: "2024-01-12",
    suggestedReorderQuantity: 20,
  },
  {
    id: 6,
    name: "Chicken Breast",
    sku: "CHI-BRE-001",
    categoryId: 3,
    categoryName: "Meat & Seafood",
    supplierId: 4,
    supplierName: "Premium Meats Ltd",
    supplierContact: "contact@premiummeats.com",
    currentStock: 2,
    lowStockThreshold: 10,
    unit: "kg",
    costPrice: 8.5,
    sellingPrice: 12.99,
    status: "low-stock" as const,
    lastRestocked: "2024-01-13",
    suggestedReorderQuantity: 25,
  },
  {
    id: 7,
    name: "Frozen Pizza",
    sku: "PIZ-FRO-001",
    categoryId: 5,
    categoryName: "Frozen Foods",
    supplierId: 5,
    supplierName: "Frozen Foods Express",
    supplierContact: "orders@frozenexpress.com",
    currentStock: 0,
    lowStockThreshold: 12,
    unit: "piece",
    costPrice: 4.2,
    sellingPrice: 8.99,
    status: "out-of-stock" as const,
    lastRestocked: "2024-01-08",
    suggestedReorderQuantity: 40,
  },
]

export const activityData = [
  {
    id: "ACT-001",
    type: "sale",
    description: "Sold 3 kg of Organic Bananas to customer",
    user: "John Cashier",
    timestamp: "2024-01-15 14:30:25",
    productName: "Organic Bananas",
    amount: 14.97,
    quantity: 3,
  },
  {
    id: "ACT-002",
    type: "refund",
    description: "Refunded 1 piece of Cheddar Cheese - customer complaint",
    user: "Sarah Manager",
    timestamp: "2024-01-15 13:45:12",
    productName: "Cheddar Cheese",
    amount: 5.99,
    quantity: 1,
  },
  {
    id: "ACT-003",
    type: "stock_in",
    description: "Received 50 kg of Organic Carrots from supplier",
    user: "Mike Warehouse",
    timestamp: "2024-01-15 10:15:30",
    productName: "Organic Carrots",
    quantity: 50,
  },
  {
    id: "ACT-004",
    type: "low_stock",
    description: "Low stock alert triggered for Red Apples",
    user: "System",
    timestamp: "2024-01-15 09:00:00",
    productName: "Red Apples",
  },
  {
    id: "ACT-005",
    type: "price_change",
    description: "Updated selling price for Whole Milk from $3.29 to $3.49",
    user: "Admin User",
    timestamp: "2024-01-15 08:30:15",
    productName: "Whole Milk",
  },
  {
    id: "ACT-006",
    type: "sale",
    description: "Sold 2 liters of Whole Milk to customer",
    user: "Emma Cashier",
    timestamp: "2024-01-14 16:20:45",
    productName: "Whole Milk",
    amount: 6.98,
    quantity: 2,
  },
  {
    id: "ACT-007",
    type: "stock_out",
    description: "Stock depleted for Frozen Pizza - marked as out of stock",
    user: "System",
    timestamp: "2024-01-14 15:45:30",
    productName: "Frozen Pizza",
  },
  {
    id: "ACT-008",
    type: "sale",
    description: "Sold 1 kg of Red Apples to customer",
    user: "John Cashier",
    timestamp: "2024-01-14 14:15:20",
    productName: "Red Apples",
    amount: 3.49,
    quantity: 1,
  },
  {
    id: "ACT-009",
    type: "refund",
    description: "Refunded 2 kg of Organic Bananas - quality issue",
    user: "Sarah Manager",
    timestamp: "2024-01-14 12:30:10",
    productName: "Organic Bananas",
    amount: 9.98,
    quantity: 2,
  },
  {
    id: "ACT-010",
    type: "stock_in",
    description: "Received 30 pieces of Cheddar Cheese from supplier",
    user: "Mike Warehouse",
    timestamp: "2024-01-14 11:00:00",
    productName: "Cheddar Cheese",
    quantity: 30,
  },
  {
    id: "ACT-011",
    type: "sale",
    description: "Sold 5 kg of Organic Bananas to customer",
    user: "Emma Cashier",
    timestamp: "2024-01-13 17:45:30",
    productName: "Organic Bananas",
    amount: 24.95,
    quantity: 5,
  },
  {
    id: "ACT-012",
    type: "low_stock",
    description: "Low stock alert triggered for Cheddar Cheese",
    user: "System",
    timestamp: "2024-01-13 16:30:00",
    productName: "Cheddar Cheese",
  },
  {
    id: "ACT-013",
    type: "sale",
    description: "Sold 3 liters of Whole Milk to customer",
    user: "John Cashier",
    timestamp: "2024-01-13 15:20:15",
    productName: "Whole Milk",
    amount: 10.47,
    quantity: 3,
  },
  {
    id: "ACT-014",
    type: "stock_in",
    description: "Received 25 kg of Red Apples from supplier",
    user: "Mike Warehouse",
    timestamp: "2024-01-13 10:30:45",
    productName: "Red Apples",
    quantity: 25,
  },
  {
    id: "ACT-015",
    type: "price_change",
    description: "Updated discount price for Organic Bananas from $4.99 to $4.49",
    user: "Admin User",
    timestamp: "2024-01-13 09:15:30",
    productName: "Organic Bananas",
  },
  {
    id: "ACT-016",
    type: "sale",
    description: "Sold 2 pieces of Cheddar Cheese to customer",
    user: "Emma Cashier",
    timestamp: "2024-01-12 18:30:20",
    productName: "Cheddar Cheese",
    amount: 11.98,
    quantity: 2,
  },
  {
    id: "ACT-017",
    type: "refund",
    description: "Refunded 1 liter of Whole Milk - expired product",
    user: "Sarah Manager",
    timestamp: "2024-01-12 16:45:10",
    productName: "Whole Milk",
    amount: 3.49,
    quantity: 1,
  },
  {
    id: "ACT-018",
    type: "stock_out",
    description: "Stock depleted for Organic Carrots - marked as out of stock",
    user: "System",
    timestamp: "2024-01-12 14:20:00",
    productName: "Organic Carrots",
  },
  {
    id: "ACT-019",
    type: "sale",
    description: "Sold 4 kg of Organic Bananas to customer",
    user: "John Cashier",
    timestamp: "2024-01-12 13:15:45",
    productName: "Organic Bananas",
    amount: 19.96,
    quantity: 4,
  },
  {
    id: "ACT-020",
    type: "low_stock",
    description: "Low stock alert triggered for Whole Milk",
    user: "System",
    timestamp: "2024-01-12 11:00:00",
    productName: "Whole Milk",
  },
  {
    id: "ACT-021",
    type: "stock_in",
    description: "Received 40 liters of Whole Milk from supplier",
    user: "Mike Warehouse",
    timestamp: "2024-01-11 15:30:20",
    productName: "Whole Milk",
    quantity: 40,
  },
  {
    id: "ACT-022",
    type: "sale",
    description: "Sold 2 kg of Red Apples to customer",
    user: "Emma Cashier",
    timestamp: "2024-01-11 14:45:30",
    productName: "Red Apples",
    amount: 6.98,
    quantity: 2,
  },
  {
    id: "ACT-023",
    type: "price_change",
    description: "Updated cost price for Cheddar Cheese from $3.25 to $3.50",
    user: "Admin User",
    timestamp: "2024-01-11 12:20:15",
    productName: "Cheddar Cheese",
  },
  {
    id: "ACT-024",
    type: "sale",
    description: "Sold 6 kg of Organic Bananas to customer",
    user: "John Cashier",
    timestamp: "2024-01-11 11:30:45",
    productName: "Organic Bananas",
    amount: 29.94,
    quantity: 6,
  },
  {
    id: "ACT-025",
    type: "refund",
    description: "Refunded 3 kg of Red Apples - customer dissatisfaction",
    user: "Sarah Manager",
    timestamp: "2024-01-10 17:15:20",
    productName: "Red Apples",
    amount: 10.47,
    quantity: 3,
  },
]

export const activityStats = {
  totalActivities: activityData.length,
  todayActivities: activityData.filter((a) => a.timestamp.startsWith("2024-01-15")).length,
  salesActivities: activityData.filter((a) => a.type === "sale").length,
  stockActivities: activityData.filter((a) => a.type === "stock_in" || a.type === "stock_out").length,
}

export async function getReorderStats() {
  await new Promise((resolve) => setTimeout(resolve, 1500))
  return reorderStats
}

export async function getProductsNeedingReorder() {
  await new Promise((resolve) => setTimeout(resolve, 2000))
  return productsNeedingReorder
}

export async function getActivityData() {
  await new Promise((resolve) => setTimeout(resolve, 1500))
  return activityData
}

export async function getActivityStats() {
  await new Promise((resolve) => setTimeout(resolve, 1000))
  return activityStats
}

export async function getCategoryStats() {
  await new Promise((resolve) => setTimeout(resolve, 1500))
  return inventoryStats
}

export async function getCategories() {
  await new Promise((resolve) => setTimeout(resolve, 2000))
  return categories
}
