export const categories = [
  {
    id: 1,
    name: "Electronics",
    description: "Electronic devices and accessories",
  },
  { id: 2, name: "Furniture", description: "Office and home furniture" },
  { id: 3, name: "Clothing", description: "Apparel and accessories" },
  { id: 4, name: "Kitchen", description: "Kitchen appliances and utensils" },
  { id: 5, name: "Sports", description: "Sports equipment and gear" },
  { id: 6, name: "Books", description: "Books and educational materials" },
];

export const suppliers = [
  {
    id: 1,
    name: "TechSupply Inc.",
    email: "contact@techsupply.com",
    phone: "+1-555-0123",
  },
  {
    id: 2,
    name: "Furniture Wholesale",
    email: "orders@furnwholesale.com",
    phone: "+1-555-0124",
  },
  {
    id: 3,
    name: "ElectroGoods Ltd.",
    email: "supply@electrogoods.com",
    phone: "+1-555-0125",
  },
  {
    id: 4,
    name: "Kitchen Essentials",
    email: "orders@kitcheness.com",
    phone: "+1-555-0126",
  },
  {
    id: 5,
    name: "SportGear Pro",
    email: "sales@sportgearpro.com",
    phone: "+1-555-0127",
  },
];

export const products = [
  {
    id: 1,
    name: "Wireless Headphones Pro",
    sku: "EL-1234",
    category: "Electronics",
    supplier: "TechSupply Inc.",
    price: 199.99,
    cost: 120.0,
    stock: 45,
    minStock: 10,
    status: "Active",
    description: "Premium wireless headphones with noise cancellation",
    image: "/placeholder.svg?height=100&width=100",
    createdAt: "2025-01-15",
    updatedAt: "2025-05-20",
  },
  {
    id: 2,
    name: "Ergonomic Office Chair",
    sku: "FN-5678",
    category: "Furniture",
    supplier: "Furniture Wholesale",
    price: 299.99,
    cost: 180.0,
    stock: 23,
    minStock: 15,
    status: "Active",
    description: "Comfortable ergonomic chair for office use",
    image: "/placeholder.svg?height=100&width=100",
    createdAt: "2025-02-10",
    updatedAt: "2025-05-18",
  },
  {
    id: 3,
    name: "Smart Watch Series 5",
    sku: "EL-9012",
    category: "Electronics",
    supplier: "TechSupply Inc.",
    price: 399.99,
    cost: 250.0,
    stock: 8,
    minStock: 8,
    status: "Low Stock",
    description: "Advanced smartwatch with health monitoring",
    image: "/placeholder.svg?height=100&width=100",
    createdAt: "2025-03-05",
    updatedAt: "2025-05-22",
  },
  {
    id: 4,
    name: "Premium Coffee Maker",
    sku: "KT-3456",
    category: "Kitchen",
    supplier: "Kitchen Essentials",
    price: 149.99,
    cost: 90.0,
    stock: 34,
    minStock: 12,
    status: "Active",
    description: "Professional-grade coffee maker with timer",
    image: "/placeholder.svg?height=100&width=100",
    createdAt: "2025-01-20",
    updatedAt: "2025-05-19",
  },
  {
    id: 5,
    name: "Bluetooth Speaker",
    sku: "EL-7890",
    category: "Electronics",
    supplier: "ElectroGoods Ltd.",
    price: 79.99,
    cost: 45.0,
    stock: 0,
    minStock: 20,
    status: "Out of Stock",
    description: "Portable Bluetooth speaker with bass boost",
    image: "/placeholder.svg?height=100&width=100",
    createdAt: "2025-02-28",
    updatedAt: "2025-05-21",
  },
  {
    id: 6,
    name: "Desk Lamp LED",
    sku: "FN-2468",
    category: "Furniture",
    supplier: "Furniture Wholesale",
    price: 59.99,
    cost: 35.0,
    stock: 67,
    minStock: 25,
    status: "Active",
    description: "Adjustable LED desk lamp with USB charging",
    image: "/placeholder.svg?height=100&width=100",
    createdAt: "2025-03-12",
    updatedAt: "2025-05-17",
  },
  {
    id: 7,
    name: "Running Shoes",
    sku: "SP-1357",
    category: "Sports",
    supplier: "SportGear Pro",
    price: 129.99,
    cost: 75.0,
    stock: 89,
    minStock: 30,
    status: "Active",
    description: "Professional running shoes with cushioning",
    image: "/placeholder.svg?height=100&width=100",
    createdAt: "2025-04-01",
    updatedAt: "2025-05-16",
  },
  {
    id: 8,
    name: "Wireless Mouse",
    sku: "EL-4680",
    category: "Electronics",
    supplier: "TechSupply Inc.",
    price: 39.99,
    cost: 22.0,
    stock: 156,
    minStock: 50,
    status: "Active",
    description: "Ergonomic wireless mouse with precision tracking",
    image: "/placeholder.svg?height=100&width=100",
    createdAt: "2025-01-08",
    updatedAt: "2025-05-23",
  },
];
